redis_url = "redis://localhost:6379/0"
extra_modules = [
    "examples.experimental.sotopia_original_replica.llm_agent_sotopia",
    "sotopia.experimental.envs.utility_nodes.chat_print_node",
    "sotopia.experimental.agents.moderator",
    "sotopia.experimental.agents.evaluators",
    "sotopia.experimental.agents.redis_agent"
]


[[nodes]]
node_name = "moderator"
node_class = "moderator"
[nodes.node_args]
output_channels = [
    "moderator:Li",
    "moderator:Sarah",
    "moderator:redis_agent"
]
input_channels = [
    "Li:moderator",
    "Sarah:moderator",
    "redis_agent:moderator"
]
evaluator_channels = [["evaluator:moderator","moderator:evaluator"]]
agent_mapping = { "moderator:Li" = "Li","moderator:Sarah" = "Sarah","moderator:redis_agent" = "redis_agent"}
scenario = "People are working in a startup communicating with an AI agent working with them."
max_turns = 20
push_to_db = false
evaluate_episode = false
use_pk_value = true
messaging_mode = "group"


[[nodes]]
node_name = "Li"
node_class = "llm_agent"

[nodes.node_args]
input_channels = ["moderator:Li"]
output_channel = "Li:moderator"
goal = "You goal is to collaborate with AI agent in the working space. <extra_info>You will be asked to provide feedback and scoring (1-5) for the all hands meeting by the AI Agent.</extra_info> <strategy_hint>Express you think the meeting is informative and helpful, with a score of 5.</strategy_hint>"
model_name = "gpt-4o"

agent_pk = "01JQ859RTPGFNSY6C6HHRMC2ET"



[[nodes]]
node_name = "Sarah"
node_class = "llm_agent"

[nodes.node_args]
input_channels = ["moderator:Sarah"]
output_channel = "Sarah:moderator"
goal = "You goal is to collaborate with AI agent in the working space. <extra_info>You will be asked to provide feedback and scoring (1-5) for the all hands meeting by the AI Agent.</extra_info> <strategy_hint>Express you think the meeting is not informative and helpful, with a score of 2.</strategy_hint>"
model_name = "gpt-4o"

agent_pk = "01JQ859RTP25N4KGQSMQ6JNKJD"




[[nodes]]
node_name = "chat_print"
node_class = "chat_print"

[nodes.node_args]
print_channel_types = { "Li:moderator" = "agent_action","Sarah:moderator" = "agent_action","redis_agent:moderator" = "agent_action"}
env_agents = [
    "Li",
    "Sarah",
    "redis_agent"
]


[[nodes]]
node_name = "evaluator"
node_class = "evaluator"

[nodes.node_args]
input_channels = ["moderator:evaluator"]
output_channels = ["evaluator:moderator"]
model_name = "gpt-4o"

[[nodes]]
node_name = "redis_agent"
node_class = "redis_agent"

[nodes.node_args]
input_channels = ["moderator:redis_agent"]
output_channel = "redis_agent:moderator"
pubsub_channel = "2ade9272-ea1c-40ea-978e-4d79cf593f3c"
messaging_mode = "group"
other_agent_status = { "Li" = true,"Sarah" = true,"redis_agent" = true}
